### PR TITLE
Docs(readme): Prettify readme

### PR DESCRIPTION
**Pull request by brutalcrozt**
- remove unnecessary line break on karma.conf.
  - add line break on badge

### CODE REVIEW

**Comment by brutalcrozt** [comment]
Hi thanks for the module, feel free to close if you don't want it. I choose doing this rather than just saying plain "thank you".

**Comment by mattlewis92** [comment]
Thanks for the contribution! I'm on the fence about this one so I've put it on a twitter poll and will let the public decide 😄 https://twitter.com/mattlewis92_/status/932695660503228418

**Comment by brutalcrozt** [comment]
😄 It's okay even i want with space in my code, but for me it better packed without space in a README. It's not big problem even this PR rejected, but let me know the reason.

**Comment by mattlewis92** [comment]
The result of the twitter poll was in favour of keeping the existing formatting, so I'm going to leave it as is. Thanks for your contribution though! 😄

**Comment by brutalcrozt** [comment]
Nvm dude, i will try contribute whenever it possible 😉 . It's okay if contact you via twitter right?

**Comment by mattlewis92** [comment]
Absolutely, I don't check social media often but I will always try and reply eventually 😄

**Pull request closed without merging**
