### PR TITLE
feat: add combinedReport option

### PR DESCRIPTION
**Pull request by bryanforbes**
Implements behavior discussed in #34

### CODE REVIEW

**Comment by mattlewis92** [comment]
Nice one, thanks for this! 😄 What do you think about a more explicit option name than `combinedReport`, maybe something like `combineBrowserReports` or `mergeBrowserReports`?

**Comment by bryanforbes** [comment]
`combineBrowserReports` sounds good. Do you want me to make the change?

**Comment by mattlewis92** [comment]
If you could that would be great! 😄

**Comment by bryanforbes** [comment]
Done :)

**Comment by mattlewis92** [comment]
Perfect, thank you 😄

**Pull request merged**
